"""Allow image_url and image_url2 to be nullable

Revision ID: 535d77fbdea0
Revises: 6114f70a6a4b
Create Date: 2025-06-10 15:38:16.595608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535d77fbdea0'
down_revision = '6114f70a6a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
