"""add kana fields

Revision ID: 6114f70a6a4b
Revises: 2d226b315328
Create Date: 2025-05-01 22:17:16.335205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6114f70a6a4b'
down_revision = '2d226b315328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ja_kana', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twin_name_ja_kana', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('twin_name_ja_kana')
        batch_op.drop_column('name_ja_kana')

    # ### end Alembic commands ###
