"""Add image_public_id columns

Revision ID: 78b8b63a424f
Revises: 535d77fbdea0
Create Date: 2025-06-23 19:30:46.201654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b8b63a424f'
down_revision = '535d77fbdea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_public_id2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('image_public_id2')
        batch_op.drop_column('image_public_id')

    # ### end Alembic commands ###
